name: Update Snapshot Date

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions: write-all

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Snapshot Date
        run: |
          sed -i -E "s/(fxcore-pruned-snapshot-mainnet-)[0-9]{4}-[0-9]{2}-[0-9]{2}/\1$(date +%Y-%m-%d)/g" ./pundi-aifx/setup-node/use-snapshot.md
          sed -i -E "s/(fxcore-pruned-snapshot-testnet-)[0-9]{4}-[0-9]{2}-[0-9]{2}/\1$(date +%Y-%m-%d)/g" ./pundi-aifx/setup-node/use-snapshot.md
          if [ "$(date +%u)" -eq 2 ]; then
            sed -i -E "s/(fxcore-snapshot-mainnet-)[0-9]{4}-[0-9]{2}-[0-9]{2}/\1$(date +%Y-%m-%d)/g" ./pundi-aifx/setup-node/use-snapshot.md
            sed -i -E "s/(fxcore-snapshot-testnet-)[0-9]{4}-[0-9]{2}-[0-9]{2}/\1$(date +%Y-%m-%d)/g" ./pundi-aifx/setup-node/use-snapshot.md
          fi

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update Snapshot Date"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}